# returns error Sending fatal Alert BadCertificate
apiVersion: lifecycle.keptn.sh/v1alpha1
kind: KeptnTaskDefinition
metadata:
  name: notify
  namespace: simplenode-dev
spec:
  function:
    inline:
      code: | 
            let body = `{"text": "Hello, world. this is a test"}`;
            console.log(body)
            let resp = await fetch("https://hooks.slack.com/services/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", {
                method: "POST",
                body,
                headers: {
                   "Content-Type": "application/json",
                   Accept: "application/json",
                },
            });
            console.log(resp)    
    secureParameters:
      secret: slack-notification